
# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "token",
    srcs = ["token.cpp"],
    hdrs = ["token.h"],
    visibility = [
        "//visibility:public",
    ],
    deps = [],
)