# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "ast",
    srcs = ["ast.cpp"],
    hdrs = ["ast.h"],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//token:token",
    ],
)